
// src/components/admin/AddEditUserDialog.tsx
'use client';

import React, { useTransition, useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogClose
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useToast } from '@/hooks/use-toast';
// createUserWithEmailAndPassword and signInWithEmailAndPassword are removed as user creation moves to server action
// import { createUserWithEmailAndPassword, signInWithEmailAndPassword } from 'firebase/auth';
// import { auth } from '@/lib/firebase';
// addDoc, collection, serverTimestamp are removed as user creation moves to server action
// import { addDoc, collection, serverTimestamp } from 'firebase/firestore';
// import { db } from '@/lib/firebase';
import type { UserRole, User, Company, Location } from '@/types/user';
// addUserToFirestore is removed, server action handles this
// import { addUser as addUserToFirestore } from '@/lib/user-data';
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"; // Import Alert components
import { AlertCircle, Loader2, Info, ShieldCheck } from 'lucide-react'; // Import AlertCircle and Info
import { createUserAndSendWelcomeEmail } from '@/actions/userManagement'; // Import the server action

const ROLE_HIERARCHY: Record<UserRole, number> = {
  'Super Admin': 5, 'Admin': 4, 'Owner': 3, 'Manager': 2, 'Staff': 1,
};
const ASSIGNABLE_ROLES_BY_ADMINS: UserRole[] = ['Admin', 'Owner', 'Manager', 'Staff'];


const userFormSchema = z.object({
  name: z.string().min(2, { message: 'Name must be at least 2 characters.' }),
  email: z.string().email({ message: 'Please enter a valid email address.' }),
  // Password is removed, will be auto-generated by server action
  role: z.string().min(1, { message: 'Please select a user role' }) as z.ZodType<UserRole>,
  companyId: z.string().min(1, { message: 'Please select an account.' }),
  assignedLocationIds: z.array(z.string()).default([]), // Locations are optional
});

type UserFormValues = z.infer<typeof userFormSchema>;

interface AddUserDialogProps {
  onUserAdded: (user: User, tempPassword?: string) => void; // tempPassword is now optional
  isOpen: boolean;
  setIsOpen: (isOpen: boolean) => void;
  companies: Company[];
  locations: Location[]; // All locations relevant to the companies the current user can see
  currentUser: User | null;
}


export function AddUserDialog({ onUserAdded, isOpen, setIsOpen, companies, locations, currentUser }: AddUserDialogProps) {
  const [isPending, startTransition] = useTransition();
  const { toast } = useToast();
  const [locationsForSelectedBrand, setLocationsForSelectedBrand] = useState<Location[]>([]);
  const [selectedCompanyDetails, setSelectedCompanyDetails] = useState<Company | null>(null);
  const [isLoadingBrandData, setIsLoadingBrandData] = useState(false); // Loading state for brand's locations

  const form = useForm<UserFormValues>({
    resolver: zodResolver(userFormSchema),
    defaultValues: { name: '', email: '', role: 'Staff', companyId: '', assignedLocationIds: [] },
  });

  const selectedCompanyIdForm = form.watch('companyId');

  // Effect to filter locations when selectedCompanyIdForm (from the dialog form) changes
  useEffect(() => {
    const updateLocationsForDialog = async () => {
      if (!selectedCompanyIdForm) {
        setSelectedCompanyDetails(null);
        setLocationsForSelectedBrand([]);
        form.setValue('assignedLocationIds', []);
        return;
      }
      setIsLoadingBrandData(true);
      try {
        // Find the company details from the passed 'companies' prop
        const companyData = companies.find(c => c.id === selectedCompanyIdForm);
        setSelectedCompanyDetails(companyData || null);
        
        // Filter the 'locations' prop based on the selectedCompanyIdForm
        const brandLocations = locations.filter(loc => loc.companyId === selectedCompanyIdForm);
        
        if (currentUser?.role === 'Manager' && currentUser.companyId === selectedCompanyIdForm && currentUser.assignedLocationIds) {
            setLocationsForSelectedBrand(brandLocations.filter(loc => currentUser.assignedLocationIds!.includes(loc.id)));
        } else {
            setLocationsForSelectedBrand(brandLocations);
        }
        
        form.setValue('assignedLocationIds', []); // Reset selections when brand changes
      } catch (error) {
        toast({ title: "Error", description: "Could not load locations for the selected brand.", variant: "destructive" });
        setSelectedCompanyDetails(null); setLocationsForSelectedBrand([]);
      } finally {
        setIsLoadingBrandData(false);
      }
    };
    if (isOpen) updateLocationsForDialog();
  }, [selectedCompanyIdForm, isOpen, currentUser, companies, locations, form, toast]); // Added locations prop


  // Effect to set initial form values when dialog opens or currentUser changes
  useEffect(() => {
    if (isOpen && currentUser) {
      const initialRole = currentUser.role === 'Manager' ? 'Staff' : 'Staff'; // Default to Staff
      let initialCompanyId = '';

      if (currentUser.role !== 'Super Admin' && currentUser.companyId) {
        initialCompanyId = currentUser.companyId;
      } else if (currentUser.role === 'Super Admin' && companies.length === 1) {
        // If Super Admin and only one company available, pre-select it
        initialCompanyId = companies[0].id;
      }
      
      form.reset({
        name: '',
        email: '',
        role: initialRole,
        companyId: initialCompanyId,
        assignedLocationIds: [],
      });
      
      // Trigger location update if initialCompanyId is set
      if (initialCompanyId) {
        form.setValue('companyId', initialCompanyId, { shouldValidate: true }); // Ensure validation triggers
      } else {
         // If no initial company (e.g., Super Admin and multiple companies), clear locations
        setLocationsForSelectedBrand([]); 
        setSelectedCompanyDetails(null);
      }
    }
  }, [isOpen, currentUser, companies, form]);


  const onSubmit = async (data: UserFormValues) => {
    startTransition(async () => {
      if (!currentUser) { toast({ title: "Error", description: "Current user not found.", variant: "destructive" }); return; }

      // Permission checks
      if (currentUser.role !== 'Super Admin') {
        if (ROLE_HIERARCHY[currentUser.role] < ROLE_HIERARCHY[data.role]) {
          toast({ title: "Permission Denied", description: "You cannot create a user with a role higher than your own.", variant: "destructive"});
          return;
        }
        if (currentUser.role === 'Manager') {
          if (!(data.role === 'Staff' || data.role === 'Manager')) { // Manager can create Staff or Manager
            toast({ title: "Permission Denied", description: "Managers can only create Staff or Manager users.", variant: "destructive"});
            return;
          }
        } else { // Admin or Owner
          if (ROLE_HIERARCHY[currentUser.role] === ROLE_HIERARCHY[data.role]) {
            toast({ title: "Permission Denied", description: "You cannot create a user with a role equal to your own.", variant: "destructive"});
            return;
          }
        }
      }
      
      if (!data.companyId) { form.setError("companyId", { type: "manual", message: "Brand selection is required." }); return; }
      // Location assignment is optional as per schema default, so no need for this check:
      // if (!data.assignedLocationIds || data.assignedLocationIds.length === 0) {
      //   form.setError("assignedLocationIds", { type: "manual", message: "User must be assigned to at least one location." });
      //   return;
      // }
      
      const userDataToSend = { // Password is not sent, handled by server action
        name: data.name,
        email: data.email,
        role: data.role,
        companyId: data.companyId,
        assignedLocationIds: data.assignedLocationIds || [], // Ensure it's an array
      };

      const result = await createUserAndSendWelcomeEmail(userDataToSend);

      if (result.success && result.user) {
        toast({ title: 'User Added & Email Sent', description: `${result.user.name} successfully added. Welcome email initiated.` });
        onUserAdded(result.user, result.tempPassword); // Pass tempPassword to parent
        setIsOpen(false);
      } else {
        toast({ title: 'User Creation Error', description: result.error || 'An unknown error occurred.', variant: 'destructive' });
      }
    });
  };

  // Filter assignable roles based on current user's role
  const assignableRoles = ASSIGNABLE_ROLES_BY_ADMINS.filter(role => {
    if (!currentUser) return false;
    if (currentUser.role === 'Super Admin') return true; // Super Admin can assign any of these roles
    if (currentUser.role === 'Manager') return role === 'Staff' || role === 'Manager'; // Manager can create Staff or Manager
    // For Admin/Owner, they can assign roles strictly lower than their own
    return ROLE_HIERARCHY[currentUser.role] > ROLE_HIERARCHY[role];
  });
  
  const isUserLimitReached = selectedCompanyDetails?.maxUsers !== null && 
                             selectedCompanyDetails?.maxUsers !== undefined &&
                             (selectedCompanyDetails.userCount || 0) >= selectedCompanyDetails.maxUsers;


  const isBrandSelectDisabled = () => {
    if (!currentUser) return true;
    if (currentUser.role === 'Super Admin') return companies.length === 0; // Disabled if SA and no companies
    return true; // For Admin, Owner, Manager, brand is pre-selected and disabled
  };

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Add New User</DialogTitle>
          <Alert variant="default" className="mt-4 border-blue-300 bg-blue-50 dark:bg-blue-900/30">
            <Info className="h-4 w-4 text-blue-600 dark:text-blue-400" />
            <AlertTitle className="text-blue-800 dark:text-blue-300">Password & Email</AlertTitle>
            <AlertDescription className="text-blue-700 dark:text-blue-400 text-xs">
              A temporary password will be auto-generated. The user will be prompted to change it on first login.
              A welcome email with these credentials will be sent to the user.
            </AlertDescription>
          </Alert>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4 py-4">
            <FormField control={form.control} name="name" render={({ field }) => ( <FormItem> <FormLabel>Full Name</FormLabel> <FormControl><Input placeholder="John Doe" {...field} /></FormControl> <FormMessage /> </FormItem> )} />
            <FormField control={form.control} name="email" render={({ field }) => ( <FormItem> <FormLabel>Email Address</FormLabel> <FormControl><Input type="email" placeholder="john.doe@example.com" {...field} /></FormControl> <FormMessage /> </FormItem> )} />
            {/* Password field removed */}
            <FormField control={form.control} name="companyId" render={({ field }) => (
              <FormItem> <FormLabel>Account</FormLabel>
                {currentUser?.role === 'Super Admin' && companies.length === 0 && ( <div className="text-sm text-muted-foreground p-2 border rounded-md flex items-center gap-2 h-10"> <AlertCircle className="h-4 w-4 text-yellow-500" /> No brands. Add one first. </div> )}
                <Select 
                  onValueChange={(value) => field.onChange(value === 'placeholder-company' ? '' : value)} 
                  value={field.value || 'placeholder-company'} 
                  disabled={isBrandSelectDisabled() || isLoadingBrandData}
                >
                  <FormControl>
                      <SelectTrigger><SelectValue placeholder="Select an account" /></SelectTrigger>
                  </FormControl>
                  <SelectContent> <SelectItem value="placeholder-company" disabled>Select an account...</SelectItem> 
                    {companies.map((c) => ( <SelectItem key={c.id} value={c.id}>{c.name} {c.parentBrandId ? "(Child)" : ""}</SelectItem> ))} 
                  </SelectContent>
                </Select>
                {isLoadingBrandData && <p className="text-xs text-muted-foreground">Loading brand info...</p>}
                {isUserLimitReached && !isLoadingBrandData && ( <p className="text-xs font-medium text-destructive">User limit reached for this brand.</p> )}
                <FormMessage />
              </FormItem> )} />
            <FormField control={form.control} name="assignedLocationIds" render={({ field }) => (
              <FormItem> <FormLabel>Assign to Locations (Optional)</FormLabel>
                <FormControl> 
                    <ScrollArea className="h-40 w-full rounded-md border p-4">
                        {isLoadingBrandData ? ( <div className="flex items-center justify-center h-full"><Loader2 className="h-5 w-5 animate-spin text-muted-foreground" /></div>
                        ) : selectedCompanyIdForm && locationsForSelectedBrand.length > 0 ? ( <div className="space-y-2"> {locationsForSelectedBrand.map((loc) => ( <FormField key={loc.id} control={form.control} name="assignedLocationIds" render={({ field: cbField }) => ( <FormItem className="flex flex-row items-start space-x-3 space-y-0"> <FormControl><Checkbox checked={cbField.value?.includes(loc.id)} onCheckedChange={(checked) => checked ? cbField.onChange([...(cbField.value || []), loc.id]) : cbField.onChange((cbField.value || []).filter(v => v !== loc.id))} id={`loc-${loc.id}`} /></FormControl> <FormLabel htmlFor={`loc-${loc.id}`} className="font-normal">{loc.name}</FormLabel> </FormItem> )}/> ))} </div>
                        ) : ( <div className="text-sm text-muted-foreground italic flex items-center justify-center h-full"> {selectedCompanyIdForm ? 'No locations for this account or your access.' : 'Select account first.'} </div> )}
                    </ScrollArea>
                </FormControl> <FormMessage />
              </FormItem> )} />

            <FormField control={form.control} name="role" render={({ field }) => (
              <FormItem> <FormLabel>User Role</FormLabel>
                <Select onValueChange={(value) => field.onChange(value === 'placeholder-role' ? '' : value)} value={field.value || 'placeholder-role'} defaultValue={field.value} disabled={assignableRoles.length === 0}>
                  <FormControl>
                        <SelectTrigger><SelectValue placeholder="Select a user role" /></SelectTrigger>
                  </FormControl>
                  <SelectContent> <SelectItem value="placeholder-role" disabled>Select a role...</SelectItem>
                    {assignableRoles.map((r) => ( <SelectItem key={r} value={r}>{r}</SelectItem> ))}
                    {/* Show roles that are not assignable as disabled */}
                    {ASSIGNABLE_ROLES_BY_ADMINS.filter(r => !assignableRoles.includes(r) && r !== 'Super Admin').map(r => ( <SelectItem key={r} value={r} disabled>{r} (Permission Denied)</SelectItem> ))}
                  </SelectContent>
                </Select>
                   <FormDescription>
                      <ul className="list-disc pl-4 text-xs space-y-1 mt-2">
                        <li><strong>Admin/Owner:</strong> Full control over their account & child accounts.</li>
                        <li><strong>Manager:</strong> Manages users within their assigned locations.</li>
                        <li><strong>Staff:</strong> Standard user, can only access assigned learning content.</li>
                      </ul>
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )} />
            
            <DialogFooter> <DialogClose asChild><Button type="button" variant="outline" onClick={() => setIsOpen(false)}>Cancel</Button></DialogClose> <Button type="submit" className="bg-primary hover:bg-primary/90" disabled={isPending || (currentUser?.role === 'Super Admin' && companies.length === 0) || isUserLimitReached || isLoadingBrandData}> {isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null} {isPending ? 'Adding...' : 'Add User'} </Button> </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
    
